from .cellphone import Cellphone as Cellphone
from .flags import Flags
from .items import Items
from .rooms import Rooms

class UndertaleFile:
    """
    This class allows reading of file[0-9] and provides most lines as attributes
    """
    raw_data: list[str]
    character_name:str
    love:int
    max_hp:int
    max_en:int
    attack_dmg:int
    weapon_strength:int
    defense:int
    armor_defense:int
    sp:int
    exp:int
    gold:int
    kills:int
    inventory_0:Items
    cell_0:Cellphone
    inventory_1:Items
    cell_1:Cellphone
    inventory_2:Items
    cell_2:Cellphone
    inventory_3:Items
    cell_3:Cellphone
    inventory_4:Items
    cell_4:Cellphone
    inventory_5:Items
    cell_5:Cellphone
    inventory_6:Items
    cell_6:Cellphone
    inventory_7:Items
    cell_7:Cellphone
    weapon_item:int
    armor_item:int
    undyne_trigger_override:int
    UNDYNE_TRIGGER_OVERRIDE:int
    hardmode:int
    true_pacifist:int
    disable_random_encounters:int
    DISABLE_RANDOM_ENCOUNTERS:int
    escaped_last:int
    killed_last:int
    bored_last:int
    status_dummy:int
    in_battle:int
    type_heart_transition:int
    TYPE_HEART_TRANSITION:int
    cooked_noodles:int
    name_color:int
    spared:int
    escaped:int
    dialogues_skipped:int
    murderlevel_override:int
    spared_specific:int
    fast_text_skip:int
    tutorial_froggit_encountered:int
    TUTORIAL_FROGGIT_ENCOUNTERED:int
    pushed_rock_2:int
    pushed_rock_3:int
    candy_taken:int
    pushed_rock_4:int
    spared_napstablook:int
    waited_toriel:int
    greeted_toriel:int
    flirted_toriel:int
    call_mom_toriel:int
    ruins_switches_pressed:int
    RUINS_SWITCHES_PRESSED:int
    status_toriel:int
    choice_flavor:int
    status_creepy_tundra:int
    know_water_sausage:int
    wrong_switches_pressed:int
    WRONG_SWITCHES_PRESSED:int
    status_dogcouple:int
    status_greaterdog:int
    status_lesserdog:int
    status_snowman:int
    status_snowdrake:int
    choice_harder_puzzle:int
    spider_donations_total:int
    SPIDER_DONATIONS_TOTAL:int
    NICECREAM_DONATIONS_TOTAL:int
    CHOICE_ATE_LEFT_SPAGHETTI:int
    toggled_snow_switch:int
    got_snowpoff_gold:int
    flirted_papyrus_fight:int
    FLIRTED_PAPYRUS_FIGHT:int
    fought_papyrus:int
    bpants_alt_dialogue:int
    progress_tundra_battles:int
    PROGRESS_TUNDRA_BATTLES:int
    stayed_inn:int
    betrayed_gyftrot:int
    armor_papyrus_inquiry:int
    ARMOR_PAPYRUS_INQUIRY:int
    CHOICE_PAPYRUS_INQUIRY:int
    strong_tough_glove:int
    nicecream_business:int
    punchcards_bought:int
    status_shyren:int
    papyrus_sink_event_occurred:int
    PAPYRUS_SINK_EVENT_OCCURRED:int
    have_umbrella:int
    music_statue_on:int
    dated_papyrus:int
    dated_sans1:int
    choice_mkid_umbrella:int
    interacted_garbage_savepoint:int
    INTERACTED_GARBAGE_SAVEPOINT:int
    dated_napstablook:int
    current_napstablook_song:int
    CURRENT_NAPSTABLOOK_SONG:int
    conversation_emblem:int
    creepy_friend_seen:int
    saved_mkid:int
    undyne_difficulty:int
    got_ribbon:int
    got_toyknife:int
    got_bscotch_pie:int
    got_quiche:int
    got_tutu:int
    got_ballet_shoes:int
    got_artifact:int
    got_spacefood:int
    got_instant_noodles:int
    got_frying_pan:int
    got_apron:int
    got_glamburger_trashcan:int
    GOT_GLAMBURGER_TRASHCAN:int
    got_dagger:int
    got_locket:int
    spared_froggit:int
    spared_whimsun:int
    spared_moldsmal:int
    spared_loox:int
    spared_vegetoid:int
    spared_migosp:int
    spared_snowdrake:int
    spared_icecap:int
    spared_gyftrot:int
    spared_doggo:int
    spared_lesserdog:int
    spared_greatdog:int
    spared_aaron:int
    spared_moldsmalx:int
    spared_woshua:int
    spared_temmie:int
    spared_maddummy:int
    spared_vulkin:int
    spared_tsunderplane:int
    spared_pyrope:int
    spared_finalfroggit:int
    spared_whimsalot:int
    spared_astigmatism:int
    spared_madjick:int
    spared_finalknight:int
    spared_endogeny:int
    conversation_toriel_pacifist:int
    CONVERSATION_TORIEL_PACIFIST:int
    CONVERSATION_SANS_PACIFIST:int
    CONVERSATION_UNDYNE_PACIFIST:int
    UNLOCK_NAPSTA_PACIFIST:int
    CONVERSATION_PAPYRUS_PACIFIST:int
    CONVERSATION_ALPHYS_PACIFIST:int
    CONVERSATION_ASGORE_PACIFIST:int
    CONVERSATION_METTATON_PACIFIST:int
    CONVERSATION_NAPSTABLOOK_PACIFIST:int
    kills_collective:int
    kills_ruins:int
    kills_tundra:int
    kills_water:int
    kills_hotland:int
    genocide_ruins:int
    genocide_tundra:int
    genocide_water:int
    genocide_hotland:int
    genocide_core:int
    nicecream_business2:int
    killed_undyne_ex:int
    killed_glad_dummy:int
    killed_snowman:int
    interacted_crosswords:int
    INTERACTED_CROSSWORDS:int
    robbed_core:int
    used_recovery_item:int
    interacted_fakedog:int
    delivered_seatea:int
    delivered_cinnabun:int
    delivered_hotdog:int
    tem_sell_parameter1:int
    tem_sell_parameter2:int
    status_hotel:int
    allergy_tem_talked:int
    glowshrooms_on:int
    fighting_sans:int
    geeettttttt_dunked_on:int
    GEEETTTTTTT_DUNKED_ON:int
    temmie_college_paid:int
    fun_call_occurred:int
    completed_tile_puzzle:int
    COMPLETED_TILE_PUZZLE:int
    conversation_elderpuzzles:int
    CONVERSATION_ELDERPUZZLES:int
    encountered_glyde:int
    check_papyrus_kitchen_again:int
    CHECK_PAPYRUS_KITCHEN_AGAIN:int
    conversation_toriel_sms:int
    CONVERSATION_TORIEL_SMS:int
    CONVERSATION_SMS_PARAMETERS:int
    stepped_green_tile:int
    dimensional_box_a_0:Items
    dimensional_box_a_1:Items
    dimensional_box_a_2:Items
    dimensional_box_a_3:Items
    dimensional_box_a_4:Items
    dimensional_box_a_5:Items
    dimensional_box_a_6:Items
    dimensional_box_a_7:Items
    dimensional_box_a_8:Items
    dimensional_box_a_9:Items
    dimensional_box_b_0:Items
    dimensional_box_b_1:Items
    dimensional_box_b_2:Items
    dimensional_box_b_3:Items
    dimensional_box_b_4:Items
    dimensional_box_b_5:Items
    dimensional_box_b_6:Items
    dimensional_box_b_7:Items
    dimensional_box_b_8:Items
    dimensional_box_b_9:Items
    status_undyne:int
    undyne_hp_left:int
    fought_undyne:int
    poured_water_ground:int
    conversation_papyrus_calls:int
    CONVERSATION_PAPYRUS_CALLS:int
    completed_piano_puzzle:int
    COMPLETED_PIANO_PUZZLE:int
    PROGRESS_WATER_BATTLES:int
    PROGRESS_WATER2_BATTLES:float
    rain_parameters_1:float
    rain_parameters_2:float
    rain_parameters_3:float
    rain_parameters_4:float
    have_water:int
    disable_alphys_calls:int
    disable_alphys_statuses:int
    DISABLE_ALPHYS_STATUSES:int
    CONVERSATION_ALPHYS_STATUSES:int
    laser1_off:int
    laser2_on:int
    laser2_off:int
    completed_shoot_puzzle1:int
    COMPLETED_SHOOT_PUZZLE1:int
    COMPLETED_SHOOT_PUZZLE2:int
    CONVEYOR_PUZZLE_VARIABLE:int
    FAILED_JETPACK_SEGMENT:int
    conversation_hotdogs:int
    headdogs:int
    reached_headdogs_limit:int
    REACHED_HEADDOGS_LIMIT:int
    muffet_bribe_money_spent:int
    MUFFET_BRIBE_MONEY_SPENT:int
    reset_bridgeseed_puzzle:int
    RESET_BRIDGESEED_PUZZLE:int
    fall_animation_parameters:int
    FALL_ANIMATION_PARAMETERS:int
    undyne_expression:int
    choice_meal_grillby:int
    bombs_defused:int
    fought_muffet:int
    killed_muffet:int
    current_elevator_floor:int
    CURRENT_ELEVATOR_FLOOR:int
    COMPLETED_SHOOT_PUZZLE3:int
    COMPLETED_SHOOT_PUZZLE4:int
    killed_rg:int
    spider_sale_big_spendings:int
    SPIDER_SALE_BIG_SPENDINGS:int
    conversation_wares:int
    conversation_mettaton:int
    CONVERSATION_METTATON:int
    progress_hotland_battles:int
    PROGRESS_HOTLAND_BATTLES:int
    GOT_NAPSTABLOOK_FRIEND_REQ:int
    got_alphys_advice1:int
    got_alphys_advice2:int
    got_alphys_advice3:int
    got_alphys_advice4:int
    progress_core_battles:int
    PROGRESS_CORE_BATTLES:int
    killed_mettaton:int
    progress_core_battles2:int
    PROGRESS_CORE_BATTLES2:int
    current_final_floor:int
    rode_long_elevator:int
    unlocked_mettaton_house:int
    UNLOCKED_METTATON_HOUSE:int
    CHOICE_FLAMEY_CHALLENGE:int
    conversation_mtt:int
    conversation_girls:int
    water_taken_amount:int
    water_wasted_amount:int
    got_gun:int
    got_cowboy_hat:int
    got_mystery_key:int
    got_face_steak:int
    progress_early_story:int
    have_castle_key1:int
    have_castle_key2:int
    unlocked_latchkey:int
    early_story_parameter1:int
    EARLY_STORY_PARAMETER1:int
    EARLY_STORY_PARAMETER2:int
    experience_cosmic_garbage:int
    EXPERIENCE_COSMIC_GARBAGE:int
    got_tem_village_hint:int
    tem_boat_version:int
    called_already:int
    papyrus_and_undyne:int
    conversation_undyne_mad:int
    CONVERSATION_UNDYNE_MAD:int
    killed_asgore:int
    completed_truelab:int
    truelab_events_0:int
    truelab_events_1:int
    truelab_events_2:int
    truelab_events_3:int
    truelab_events_4:int
    truelab_events_5:int
    truelab_events_6:int
    truelab_events_7:int
    truelab_events_8:int
    truelab_events_9:int
    truelab_events_10:int
    truelab_events_11:int
    dated_alphys:int
    status_undyne_letter:int
    popato_chisps_bought:int
    conversation_onionsan:int
    CONVERSATION_ONIONSAN:int
    seen_cast:int
    fighting_asriel:int
    conversation_asriel_fight:int
    CONVERSATION_ASRIEL_FIGHT:int
    dreamed_asriel_fight:int
    saved_lost_soul_0:int
    saved_lost_soul_1:int
    saved_lost_soul_2:int
    saved_lost_soul_3:int
    toggle_final_beam:int
    plot_over:int
    conversation_asriel2:int
    plot:float
    menuchoice_0:int
    menuchoice_1:int
    menuchoice_2:int
    song:int
    room:Rooms
    game_time:int
    def __init__(self, path: str) -> None: ...
    def getLineStr(self, flag: Flags) -> str: ...
    def getLineInt(self, flag: Flags) -> int: ...
    def getLineFloat(self, flag: Flags) -> float: ...
    def getLineItem(self, flag: Flags) -> Items: ...
    def getLineCell(self, flag: Flags) -> Cellphone: ...
    def getLineRoom(self, flag: Flags) -> Rooms: ...
    def compare_to(self, other: UndertaleFile) -> list[str]: ...
    @property
    def inventory(self) -> list[Items]: ...
    @property
    def dim_box_a(self) -> list[Items]: ...
    @property
    def dim_box_b(self) -> list[Items]: ...
    @property
    def cellphone(self) -> list[Cellphone]: ...
    def __eq__(self, value: object) -> bool: ...
