from __future__ import annotations

from .cellphone import Cellphone
from .items import Items
from .rooms import Rooms
from .flags import Flags


class UndertaleFile:
    """
    This class allows reading of file[0-9] and provides most lines as attributes
    """
    def __init__(self, path: str) -> None: ...
    raw_data: list[str]
    def _parse(self) -> None: ...

    def getLineStr(self, flag: Flags) -> str: ...
    def getLineInt(self, flag: Flags) -> int: ...
    def getLineFloat(self, flag: Flags) -> float: ...
    def getLineItem(self, flag: Flags) -> Items: ...
    def getLineCell(self, flag: Flags) -> Cellphone: ...
    def getLineRoom(self, flag: Flags) -> Rooms: ...

    character_name: str
    love: int
    max_hp: int
    max_en: int
    attack_dmg: int
    weapon_strength: int
    defense: int
    armor_defense: int
    sp: int
    exp: int
    gold: int
    kills: int
    inventory_0: Items
    cell_0: Cellphone
    inventory_1: Items
    cell_1: Cellphone
    inventory_2: Items
    cell_2: Cellphone
    inventory_3: Items
    cell_3: Cellphone
    inventory_4: Items
    cell_4: Cellphone
    inventory_5: Items
    cell_5: Cellphone
    inventory_6: Items
    cell_6: Cellphone
    inventory_7: Items
    cell_7: Cellphone
    weapon_item: int
    armor_item: int
    undyne_trigger_override: int
    fun: int
    hardmode: int
    true_pacifist: int
    disable_random_encounters: int
    spared_last: int
    escaped_last: int
    killed_last: int
    bored_last: int
    status_dummy: int
    in_battle: int
    type_heart_transition: int
    animation_index: int
    cooked_noodles: int
    name_color: int
    spared: int
    escaped: int
    dialogues_skipped: int
    murderlevel_override: int
    spared_specific: int
    fast_text_skip: int
    tutorial_froggit_encountered: int
    pushed_rock_1: int
    pushed_rock_2: int
    pushed_rock_3: int
    candy_taken: int
    pushed_rock_4: int
    spared_napstablook: int
    waited_toriel: int
    greeted_toriel: int
    flirted_toriel: int
    call_mom_toriel: int
    ruins_switches_pressed: int
    disobeyed_toriel: int
    status_toriel: int
    choice_flavor: int
    status_creepy_tundra: int
    know_water_sausage: int
    wrong_switches_pressed: int
    status_doggo: int
    status_dogcouple: int
    status_greaterdog: int
    status_lesserdog: int
    status_snowman: int
    status_snowdrake: int
    choice_harder_puzzle: int
    spider_donations_total: int
    nicecream_donations_total: int
    choice_ate_left_spaghetti: int
    xoxo_resets: int
    toggled_snow_switch: int
    got_snowpoff_gold: int
    flirted_papyrus_fight: int
    status_papyrus: int
    fought_papyrus: int
    bpants_alt_dialogue: int
    progress_tundra_battles: int
    status_inn: int
    stayed_inn: int
    betrayed_gyftrot: int
    armor_papyrus_inquiry: int
    choice_papyrus_inquiry: int
    armor_undyne_saw: int
    strong_tough_glove: int
    nicecream_business: int
    punchcards_bought: int
    status_shyren: int
    papyrus_sink_event_occurred: int
    got_couch_gold: int
    have_umbrella: int
    music_statue_on: int
    dated_papyrus: int
    dated_sans1: int
    choice_mkid_umbrella: int
    interacted_garbage_savepoint: int
    status_stable: int
    talked_napstablook: int
    current_napstablook_song: int
    aaron_woshua_event: int
    conversation_emblem: int
    creepy_friend_seen: int
    saved_mkid: int
    undyne_difficulty: int
    got_ribbon: int
    got_toyknife: int
    got_bscotch_pie: int
    got_quiche: int
    got_tutu: int
    got_ballet_shoes: int
    got_artifact: int
    got_spacefood: int
    got_instant_noodles: int
    got_frying_pan: int
    got_apron: int
    got_glamburger_trashcan: int
    got_gold_trashcan: int
    got_dagger: int
    got_locket: int
    spared_froggit: int
    spared_whimsun: int
    spared_moldsmal: int
    spared_loox: int
    spared_vegetoid: int
    spared_migosp: int
    spared_snowdrake: int
    spared_icecap: int
    spared_gyftrot: int
    spared_doggo: int
    spared_lesserdog: int
    spared_greatdog: int
    spared_aaron: int
    spared_moldsmalx: int
    spared_woshua: int
    spared_temmie: int
    spared_maddummy: int
    spared_vulkin: int
    spared_tsunderplane: int
    spared_pyrope: int
    spared_finalfroggit: int
    spared_whimsalot: int
    spared_astigmatism: int
    spared_madjick: int
    spared_finalknight: int
    spared_endogeny: int
    conversation_toriel_pacifist: int
    conversation_sans_pacifist: int
    conversation_undyne_pacifist: int
    unlock_napsta_pacifist: int
    conversation_papyrus_pacifist: int
    conversation_alphys_pacifist: int
    conversation_asgore_pacifist: int
    conversation_mettaton_pacifist: int
    conversation_napstablook_pacifist: int
    kills_area_pointer: int
    kills_other: int
    kills_ruins: int
    kills_tundra: int
    kills_water: int
    kills_hotland: int
    genocide_ruins: int
    genocide_tundra: int
    genocide_water: int
    genocide_hotland: int
    genocide_core: int
    nicecream_business2: int
    killed_undyne_ex: int
    killed_glad_dummy: int
    killed_snowman: int
    interacted_crosswords: int
    robbed_snowdin: int
    robbed_core: int
    used_recovery_item: int
    interacted_fakedog: int
    delivered_seatea: int
    delivered_cinnabun: int
    delivered_hotdog: int
    tem_sell_parameter1: int
    tem_sell_parameter2: int
    status_hotel: int
    allergy_tem_talked: int
    glowshrooms_on: int
    fighting_sans: int
    geeettttttt_dunked_on: int
    tundra_stick_broken: int
    temmie_college_paid: int
    fun_call_occurred: int
    completed_tile_puzzle: int
    interacted_clamgirl: int
    conversation_elderpuzzles: int
    status_sosorry: int
    encountered_glyde: int
    check_papyrus_kitchen_again: int
    undyne_spears_anger: int
    conversation_toriel_sms: int
    conversation_sms_parameters: int
    failed_defusing: int
    stepped_green_tile: int
    dimensional_box_a_0: Items
    dimensional_box_a_1: Items
    dimensional_box_a_2: Items
    dimensional_box_a_3: Items
    dimensional_box_a_4: Items
    dimensional_box_a_5: Items
    dimensional_box_a_6: Items
    dimensional_box_a_7: Items
    dimensional_box_a_8: Items
    dimensional_box_a_9: Items
    dimensional_box_b_0: Items
    dimensional_box_b_1: Items
    dimensional_box_b_2: Items
    dimensional_box_b_3: Items
    dimensional_box_b_4: Items
    dimensional_box_b_5: Items
    dimensional_box_b_6: Items
    dimensional_box_b_7: Items
    dimensional_box_b_8: Items
    dimensional_box_b_9: Items
    status_undyne: int
    undyne_hp_left: int
    fought_undyne: int
    poured_water_ground: int
    conversation_papyrus_calls: int
    choice_maddummy: int
    completed_piano_puzzle: int
    progress_water_battles: int
    progress_water2_battles: int
    rain_parameters_0: float
    rain_parameters_1: float
    rain_parameters_2: float
    rain_parameters_3: float
    rain_parameters_4: float
    have_water: int
    disable_alphys_calls: int
    disable_alphys_statuses: int
    conversation_alphys_statuses: int
    quick_battle: int
    laser1_off: int
    laser2_on: int
    laser2_off: int
    completed_shoot_puzzle1: int
    completed_shoot_puzzle2: int
    conveyor_puzzle_variable: int
    failed_jetpack_segment: int
    hot_dogs_money_spent: int
    conversation_hotdogs: int
    headdogs: int
    reached_headdogs_limit: int
    muffet_bribe_price: int
    muffet_bribe_money_spent: int
    status_yellow_button: int
    reset_bridgeseed_puzzle: int
    won_ball_game: int
    fall_animation_parameters: int
    dated_undyne: int
    undyne_expression: int
    choice_meal_grillby: int
    bombs_defused: int
    fought_muffet: int
    killed_muffet: int
    current_elevator_floor: int
    completed_shoot_puzzle3: int
    completed_shoot_puzzle4: int
    asked_papyrus_rg: int
    killed_rg: int
    spider_sale_big_spendings: int
    laser3_off: int
    conversation_wares: int
    conversation_mettaton: int
    conversation_alphys: int
    progress_hotland_battles: int
    got_napstablook_friend_req: int
    dated_sans2: int
    got_alphys_advice1: int
    got_alphys_advice2: int
    got_alphys_advice3: int
    got_alphys_advice4: int
    progress_core_battles: int
    turn_mettaton: int
    killed_mettaton: int
    progress_core_battles2: int
    alphys_expression: int
    current_final_floor: int
    rode_long_elevator: int
    unlocked_mettaton_house: int
    choice_flamey_challenge: int
    status_bpants: int
    conversation_mtt: int
    conversation_girls: int
    water_taken_amount: int
    water_wasted_amount: int
    got_gun: int
    got_cowboy_hat: int
    got_mystery_key: int
    got_face_steak: int
    progress_early_story: int
    have_castle_key1: int
    have_castle_key2: int
    unlocked_latchkey: int
    early_story_parameter1: int
    early_story_parameter2: int
    told_asgore_ready: int
    experience_cosmic_garbage: int
    riverman_destination: int
    got_tem_village_hint: int
    tem_boat_version: int
    called_already: int
    papyrus_and_undyne: int
    conversation_undyne_mad: int
    killed_flowey: int
    killed_asgore: int
    completed_truelab: int
    truelab_events_0: int
    truelab_events_1: int
    truelab_events_2: int
    truelab_events_3: int
    truelab_events_4: int
    truelab_events_5: int
    truelab_events_6: int
    truelab_events_7: int
    truelab_events_8: int
    truelab_events_9: int
    truelab_events_10: int
    truelab_events_11: int
    dated_alphys: int
    status_undyne_letter: int
    popato_chisps_bought: int
    conversation_onionsan: int
    got_sans_room_key: int
    seen_cast: int
    fighting_asriel: int
    conversation_asriel_fight: int
    but_it_refused: int
    dreamed_asriel_fight: int
    saved_lost_soul_0: int
    saved_lost_soul_1: int
    saved_lost_soul_2: int
    saved_lost_soul_3: int
    toggle_final_beam: int
    plot_over: int
    conversation_asriel2: int
    choice_left_toriel: int
    plot: float
    menuchoice_0: int
    menuchoice_1: int
    menuchoice_2: int
    song: int
    room: Rooms
    game_time: int

    def compare_to(self, other: UndertaleFile) -> list[str]: ...
    @property
    def inventory(self) -> list[Items]: ...
    @property
    def dim_box_a(self) -> list[Items]: ...
    @property
    def dim_box_b(self) -> list[Items]: ...
    @property
    def cellphone(self) -> list[Cellphone]: ...
